// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMCNWEI5MUJslROE_j8Yn_muTc8fi86Co',
    appId: '1:72297304370:web:539cd7ac9037f28376872b',
    messagingSenderId: '72297304370',
    projectId: 'boom-boom-b73b2',
    authDomain: 'boom-boom-b73b2.firebaseapp.com',
    storageBucket: 'boom-boom-b73b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7w0d_J9MpbmC5GnxVsCyLHKfUKSLXuA',
    appId: '1:72297304370:android:e201f2af84b84b8e76872b',
    messagingSenderId: '72297304370',
    projectId: 'boom-boom-b73b2',
    storageBucket: 'boom-boom-b73b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfR4i951ZnDoSrS4KbTcG5iuN2ZeJKl4g',
    appId: '1:72297304370:ios:dd4e622fd54d60e376872b',
    messagingSenderId: '72297304370',
    projectId: 'boom-boom-b73b2',
    storageBucket: 'boom-boom-b73b2.appspot.com',
    iosClientId: '72297304370-iill679of1cme02oev7r5mu1s09fdith.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomBoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfR4i951ZnDoSrS4KbTcG5iuN2ZeJKl4g',
    appId: '1:72297304370:ios:dd4e622fd54d60e376872b',
    messagingSenderId: '72297304370',
    projectId: 'boom-boom-b73b2',
    storageBucket: 'boom-boom-b73b2.appspot.com',
    iosClientId: '72297304370-iill679of1cme02oev7r5mu1s09fdith.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomBoom',
  );
}
